// src/lib/ai/loginBriefing.ts
// Generates the short text briefing shown at the top of /super-admin/hq.
// Deliberately self-contained rather than importing from the large
// agent-tool machinery in /api/ai/chat/route.ts - this only needs one
// short plain-text completion, no tools, no chat history.

import Anthropic from '@anthropic-ai/sdk'
import { GoogleGenAI } from '@google/genai'

export interface HqStats {
  loginsToday: number
  loginsYesterday: number
  loginsLast7Days: number
  activeSchoolsLast7Days: number
  topRoleLast7Days: string | null
}

function buildPrompt(stats: HqStats): string {
  return `You are a terse operations analyst for a school-management SaaS platform. Given today's usage stats, write a 2-3 sentence plain-text briefing for the platform owner who just logged in. No greeting, no markdown, no headers - just the numbers in context and one notable trend or flag if there genuinely is one. If nothing stands out, say so plainly instead of inventing a trend.

Stats:
- Logins today: ${stats.loginsToday}
- Logins yesterday: ${stats.loginsYesterday}
- Logins in the last 7 days: ${stats.loginsLast7Days}
- Distinct active schools in the last 7 days: ${stats.activeSchoolsLast7Days}
- Most active role in the last 7 days: ${stats.topRoleLast7Days ?? 'n/a'}`
}

function fallbackSummary(stats: HqStats): string {
  return `${stats.loginsToday} logins today (${stats.loginsYesterday} yesterday), ${stats.loginsLast7Days} over the last 7 days across ${stats.activeSchoolsLast7Days} active school${stats.activeSchoolsLast7Days === 1 ? '' : 's'}.`
}

export async function generateLoginBriefing(stats: HqStats): Promise<string> {
  const prompt = buildPrompt(stats)

  try {
    const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })
    const response = await anthropic.messages.create({
      model: 'claude-sonnet-5',
      max_tokens: 200,
      messages: [{ role: 'user', content: prompt }],
    })
    const textBlock = response.content.find(b => b.type === 'text')
    if (textBlock && 'text' in textBlock && textBlock.text.trim()) return textBlock.text.trim()
    throw new Error('No text content in Claude response')
  } catch (claudeErr) {
    // Fall through to Gemini regardless of the specific error - a dead
    // briefing is worse than one generated by the backup provider, and
    // this endpoint has no user-facing retry button to react to the
    // distinction the way the main chat route does.
    void claudeErr
    try {
      const key = process.env.GEMINI_API_KEY
      if (!key) throw new Error('GEMINI_API_KEY not set')
      const genai = new GoogleGenAI({ apiKey: key })
      const chat = genai.chats.create({ model: 'gemini-3.6-flash' })
      const response = await chat.sendMessage({ message: prompt })
      const text = (response.text ?? '').trim()
      return text || fallbackSummary(stats)
    } catch {
      return fallbackSummary(stats)
    }
  }
}
