-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.classes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  level USER-DEFINED,
  section text NOT NULL,
  stream USER-DEFINED,
  academic_year text NOT NULL,
  class_teacher_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  school_id uuid,
  capacity integer DEFAULT 40,
  class_level text,
  is_active boolean DEFAULT true,
  name text,
  CONSTRAINT classes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.student_profiles (
  id uuid NOT NULL,
  class_id uuid,
  admission_number text NOT NULL UNIQUE,
  year_of_entry integer NOT NULL,
  stream USER-DEFINED,
  promoted_by uuid,
  promoted_at timestamp with time zone,
  guardian_name text,
  guardian_phone text,
  lifecycle_stage text NOT NULL DEFAULT 'enrolled'::text CHECK (lifecycle_stage = ANY (ARRAY['enrolled'::text, 'graduated'::text, 'alumni'::text, 'transferred'::text, 'dropped'::text])),
  graduation_year integer,
  student_number text DEFAULT admission_number,
  CONSTRAINT student_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT student_profiles_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id)
);
CREATE TABLE public.teacher_profiles (
  id uuid NOT NULL,
  staff_id text NOT NULL UNIQUE,
  subjects ARRAY,
  qualifications text,
  joined_date date,
  CONSTRAINT teacher_profiles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.parent_profiles (
  id uuid NOT NULL,
  occupation text,
  relationship text,
  CONSTRAINT parent_profiles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.parent_student_links (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  parent_id uuid NOT NULL,
  student_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT parent_student_links_pkey PRIMARY KEY (id)
);
CREATE TABLE public.school_branding (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  school_name text NOT NULL,
  tagline text,
  primary_color text NOT NULL DEFAULT '#800020'::text,
  secondary_color text,
  accent_color text,
  logo_url text,
  favicon_url text,
  login_bg_image text,
  font_family text NOT NULL DEFAULT 'Inter'::text,
  address text,
  phone text,
  website text,
  country text NOT NULL DEFAULT 'Nigeria'::text,
  currency_primary USER-DEFINED NOT NULL DEFAULT 'NGN'::currency_code,
  currency_secondary USER-DEFINED DEFAULT 'USD'::currency_code,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT school_branding_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  school_id uuid NOT NULL,
  plan_type USER-DEFINED NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'Trial'::subscription_status,
  billing_cycle USER-DEFINED NOT NULL DEFAULT 'Termly'::billing_cycle,
  started_at date NOT NULL DEFAULT CURRENT_DATE,
  expiry_date date NOT NULL,
  amount_paid numeric,
  currency_used USER-DEFINED DEFAULT 'NGN'::currency_code,
  payment_reference text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  school_registry_id uuid,
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.school_branding(id)
);
CREATE TABLE public.feature_flags (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  school_id uuid NOT NULL,
  feature_name text NOT NULL,
  is_enabled boolean NOT NULL DEFAULT false,
  enabled_by uuid,
  enabled_at timestamp with time zone,
  notes text,
  CONSTRAINT feature_flags_pkey PRIMARY KEY (id),
  CONSTRAINT feature_flags_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.school_branding(id)
);
CREATE TABLE public.fee_structures (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  class_id uuid NOT NULL,
  term USER-DEFINED NOT NULL,
  academic_year text NOT NULL,
  description text NOT NULL,
  amount_ngn numeric NOT NULL,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  school_id uuid,
  CONSTRAINT fee_structures_pkey PRIMARY KEY (id),
  CONSTRAINT fee_structures_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT fee_structures_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.payment_invoices (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  student_id uuid NOT NULL,
  fee_structure_id uuid NOT NULL,
  amount_due_ngn numeric NOT NULL,
  amount_paid_ngn numeric NOT NULL DEFAULT 0,
  balance_ngn numeric NOT NULL DEFAULT 0,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::payment_status,
  due_date date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  school_id uuid,
  last_paystack_reference text,
  CONSTRAINT payment_invoices_pkey PRIMARY KEY (id),
  CONSTRAINT payment_invoices_fee_structure_id_fkey FOREIGN KEY (fee_structure_id) REFERENCES public.fee_structures(id),
  CONSTRAINT payment_invoices_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT payment_invoices_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  invoice_id uuid,
  student_id uuid NOT NULL,
  received_by uuid,
  amount_paid_ngn numeric NOT NULL,
  amount_paid_usd numeric,
  currency_used USER-DEFINED NOT NULL DEFAULT 'NGN'::currency_code,
  exchange_rate numeric,
  receipt_number text NOT NULL UNIQUE,
  payment_method text,
  payment_reference text,
  notes text,
  paid_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  school_id uuid,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.payment_invoices(id),
  CONSTRAINT payments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT payments_received_by_fkey FOREIGN KEY (received_by) REFERENCES public.profiles(id),
  CONSTRAINT payments_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.exchange_rates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  from_currency USER-DEFINED NOT NULL,
  to_currency USER-DEFINED NOT NULL,
  rate numeric NOT NULL,
  fetched_at timestamp with time zone NOT NULL DEFAULT now(),
  currency_pair text,
  usd_rate numeric,
  CONSTRAINT exchange_rates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.digital_receipts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  payment_id uuid NOT NULL,
  student_id uuid NOT NULL,
  receipt_url text NOT NULL,
  generated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT digital_receipts_pkey PRIMARY KEY (id),
  CONSTRAINT digital_receipts_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id)
);
CREATE TABLE public.fee_reminders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  invoice_id uuid NOT NULL,
  parent_id uuid NOT NULL,
  channel USER-DEFINED NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::reminder_status,
  message_body text,
  sent_at timestamp with time zone,
  triggered_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fee_reminders_pkey PRIMARY KEY (id),
  CONSTRAINT fee_reminders_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.payment_invoices(id),
  CONSTRAINT fee_reminders_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.profiles(id),
  CONSTRAINT fee_reminders_triggered_by_fkey FOREIGN KEY (triggered_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.class_subjects (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  class_id uuid NOT NULL,
  subject_id uuid NOT NULL,
  teacher_id uuid,
  CONSTRAINT class_subjects_pkey PRIMARY KEY (id),
  CONSTRAINT class_subjects_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT class_subjects_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id)
);
CREATE TABLE public.results (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  student_id uuid NOT NULL,
  class_subject_id uuid NOT NULL,
  term USER-DEFINED NOT NULL,
  academic_year text NOT NULL,
  result_type USER-DEFINED NOT NULL,
  score numeric,
  max_score numeric NOT NULL DEFAULT 100,
  grade text,
  remarks text,
  posted_by uuid,
  posted_at timestamp with time zone NOT NULL DEFAULT now(),
  school_id uuid,
  approved boolean NOT NULL DEFAULT false,
  approved_by uuid,
  approved_at timestamp with time zone,
  CONSTRAINT results_pkey PRIMARY KEY (id),
  CONSTRAINT results_class_subject_id_fkey FOREIGN KEY (class_subject_id) REFERENCES public.class_subjects(id),
  CONSTRAINT results_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.assignments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  class_subject_id uuid,
  title text NOT NULL,
  description text,
  file_url text,
  due_date timestamp with time zone NOT NULL,
  max_score numeric DEFAULT 100,
  posted_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  school_id uuid,
  class_id uuid,
  teacher_id uuid,
  class_level text,
  created_by uuid,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'archived'::text])),
  subject text,
  submission_count integer DEFAULT 0,
  total_students integer DEFAULT 0,
  CONSTRAINT assignments_pkey PRIMARY KEY (id),
  CONSTRAINT assignments_class_subject_id_fkey FOREIGN KEY (class_subject_id) REFERENCES public.class_subjects(id),
  CONSTRAINT assignments_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT assignments_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.profiles(id),
  CONSTRAINT assignments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.assignment_submissions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  assignment_id uuid NOT NULL,
  student_id uuid NOT NULL,
  file_url text,
  text_response text,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::submission_status,
  score numeric,
  feedback text,
  submitted_at timestamp with time zone,
  graded_at timestamp with time zone,
  graded_by uuid,
  answer_text text,
  CONSTRAINT assignment_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT assignment_submissions_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.assignments(id),
  CONSTRAINT assignment_submissions_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.quizzes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  class_subject_id uuid,
  title text NOT NULL,
  description text,
  starts_at timestamp with time zone NOT NULL,
  ends_at timestamp with time zone NOT NULL,
  total_marks numeric DEFAULT 100,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  scheduled_at timestamp with time zone,
  closes_at timestamp with time zone,
  attempt_limit integer NOT NULL DEFAULT 1,
  class_id uuid,
  teacher_id uuid,
  subject text,
  duration_mins integer DEFAULT 30,
  status text DEFAULT 'draft'::text,
  school_id uuid,
  CONSTRAINT quizzes_pkey PRIMARY KEY (id),
  CONSTRAINT quizzes_class_subject_id_fkey FOREIGN KEY (class_subject_id) REFERENCES public.class_subjects(id),
  CONSTRAINT quizzes_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT quizzes_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.timetable (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  class_id uuid NOT NULL,
  class_subject_id uuid NOT NULL,
  day_of_week integer NOT NULL CHECK (day_of_week >= 1 AND day_of_week <= 5),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  room text,
  academic_year text NOT NULL,
  school_id uuid,
  term text,
  teacher_id uuid,
  CONSTRAINT timetable_pkey PRIMARY KEY (id),
  CONSTRAINT timetable_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT timetable_class_subject_id_fkey FOREIGN KEY (class_subject_id) REFERENCES public.class_subjects(id),
  CONSTRAINT timetable_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.school_notes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  class_subject_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  file_url text,
  term USER-DEFINED NOT NULL,
  academic_year text NOT NULL,
  uploaded_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  school_id uuid,
  content text,
  class_id uuid,
  visibility text DEFAULT 'class'::text CHECK (visibility = ANY (ARRAY['school'::text, 'class'::text])),
  CONSTRAINT school_notes_pkey PRIMARY KEY (id),
  CONSTRAINT school_notes_class_subject_id_fkey FOREIGN KEY (class_subject_id) REFERENCES public.class_subjects(id),
  CONSTRAINT school_notes_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id)
);
CREATE TABLE public.syllabus (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  class_id uuid NOT NULL,
  term USER-DEFINED NOT NULL,
  academic_year text NOT NULL,
  file_url text,
  uploaded_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  school_id uuid,
  CONSTRAINT syllabus_pkey PRIMARY KEY (id),
  CONSTRAINT syllabus_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT syllabus_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.online_classes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  class_subject_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  meeting_url text,
  recording_url text,
  is_live boolean NOT NULL DEFAULT false,
  scheduled_at timestamp with time zone,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  school_id uuid,
  class_id uuid,
  teacher_id uuid,
  started_at timestamp with time zone,
  ended_at timestamp with time zone,
  CONSTRAINT online_classes_pkey PRIMARY KEY (id),
  CONSTRAINT online_classes_class_subject_id_fkey FOREIGN KEY (class_subject_id) REFERENCES public.class_subjects(id),
  CONSTRAINT online_classes_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT online_classes_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.attendance (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  class_id uuid NOT NULL,
  student_id uuid NOT NULL,
  date date NOT NULL,
  is_present boolean NOT NULL DEFAULT false,
  marked_by uuid,
  notes text,
  status text DEFAULT 'present'::text,
  teacher_id uuid,
  school_id uuid,
  CONSTRAINT attendance_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT attendance_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.announcements (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title text NOT NULL,
  body text NOT NULL,
  target_audience USER-DEFINED NOT NULL DEFAULT 'all'::announcement_target,
  target_class_id uuid,
  posted_by uuid,
  is_pinned boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  school_id uuid,
  audience text NOT NULL DEFAULT 'all'::text CHECK (audience = ANY (ARRAY['all'::text, 'students'::text, 'parents'::text, 'teachers'::text, 'staff'::text])),
  status text NOT NULL DEFAULT 'published'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text])),
  author_id uuid,
  created_by uuid,
  type text DEFAULT 'general'::text,
  priority text NOT NULL DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['normal'::text, 'urgent'::text])),
  CONSTRAINT announcements_pkey PRIMARY KEY (id),
  CONSTRAINT announcements_target_class_id_fkey FOREIGN KEY (target_class_id) REFERENCES public.classes(id),
  CONSTRAINT announcements_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.profiles(id),
  CONSTRAINT announcements_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.online_meetings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title text NOT NULL,
  description text,
  meeting_url text,
  target_audience USER-DEFINED NOT NULL,
  scheduled_at timestamp with time zone NOT NULL,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  meeting_type text DEFAULT 'general'::text,
  location text,
  agenda text,
  school_id uuid,
  target_class_id uuid,
  CONSTRAINT online_meetings_pkey PRIMARY KEY (id),
  CONSTRAINT online_meetings_target_class_id_fkey FOREIGN KEY (target_class_id) REFERENCES public.classes(id),
  CONSTRAINT online_meetings_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.student_leaderboard (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  student_id uuid NOT NULL,
  class_id uuid NOT NULL,
  term USER-DEFINED NOT NULL,
  academic_year text NOT NULL,
  total_points integer NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  school_id uuid,
  CONSTRAINT student_leaderboard_pkey PRIMARY KEY (id),
  CONSTRAINT student_leaderboard_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id)
);
CREATE TABLE public.teacher_activity_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  teacher_id uuid NOT NULL,
  action text NOT NULL,
  reference_id uuid,
  reference_table text,
  logged_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT teacher_activity_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.nin_verification_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  passport_url text NOT NULL,
  nin_url text NOT NULL,
  match_confidence numeric,
  passed boolean,
  failure_reason text,
  verified_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT nin_verification_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.portal_audit_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  actor_id uuid,
  action text NOT NULL,
  target_table text,
  target_id uuid,
  ip_address text,
  user_agent text,
  metadata jsonb,
  logged_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT portal_audit_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.platform_admins (
  id uuid NOT NULL,
  full_name text NOT NULL,
  email text NOT NULL UNIQUE,
  is_super boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  pin_hash text,
  last_login timestamp with time zone,
  CONSTRAINT platform_admins_pkey PRIMARY KEY (id),
  CONSTRAINT platform_admins_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.chat_rooms (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  school_id uuid,
  room_type USER-DEFINED NOT NULL,
  name text,
  is_group boolean NOT NULL DEFAULT false,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  class_id uuid,
  posting_mode text NOT NULL DEFAULT 'moderators_only'::text CHECK (posting_mode = ANY (ARRAY['everyone'::text, 'moderators_only'::text])),
  CONSTRAINT chat_rooms_pkey PRIMARY KEY (id),
  CONSTRAINT chat_rooms_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id)
);
CREATE TABLE public.chat_room_members (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  room_id uuid NOT NULL,
  user_id uuid NOT NULL,
  joined_at timestamp with time zone NOT NULL DEFAULT now(),
  last_read_at timestamp with time zone,
  CONSTRAINT chat_room_members_pkey PRIMARY KEY (id),
  CONSTRAINT chat_room_members_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.chat_rooms(id)
);
CREATE TABLE public.chat_messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  room_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  school_id uuid,
  content text,
  file_url text,
  file_type text,
  is_edited boolean NOT NULL DEFAULT false,
  is_deleted boolean NOT NULL DEFAULT false,
  edited_at timestamp with time zone,
  reply_to_id uuid,
  sent_at timestamp with time zone NOT NULL DEFAULT now(),
  reactions jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.chat_rooms(id),
  CONSTRAINT chat_messages_reply_to_id_fkey FOREIGN KEY (reply_to_id) REFERENCES public.chat_messages(id),
  CONSTRAINT chat_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.message_read_receipts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  message_id uuid NOT NULL,
  user_id uuid NOT NULL,
  read_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT message_read_receipts_pkey PRIMARY KEY (id),
  CONSTRAINT message_read_receipts_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.chat_messages(id)
);
CREATE TABLE public.ai_conversations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  school_id uuid,
  role_context USER-DEFINED NOT NULL,
  title text,
  is_archived boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_conversations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ai_messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  conversation_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['user'::text, 'assistant'::text])),
  content text NOT NULL,
  tokens_used integer,
  sent_at timestamp with time zone NOT NULL DEFAULT now(),
  image_url text,
  model_used text,
  CONSTRAINT ai_messages_pkey PRIMARY KEY (id),
  CONSTRAINT ai_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.ai_conversations(id)
);
CREATE TABLE public.study_schedules (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  student_id uuid NOT NULL,
  school_id uuid,
  subject_id uuid,
  day_of_week integer NOT NULL CHECK (day_of_week >= 1 AND day_of_week <= 7),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  duration_mins integer NOT NULL,
  label text,
  is_active boolean NOT NULL DEFAULT true,
  created_by_ai boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT study_schedules_pkey PRIMARY KEY (id)
);
CREATE TABLE public.student_transfers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  student_id uuid NOT NULL,
  origin_school_id uuid NOT NULL,
  destination_school_id uuid NOT NULL,
  initiated_by uuid NOT NULL,
  approved_by uuid,
  rejected_by uuid,
  status USER-DEFINED NOT NULL DEFAULT 'requested'::transfer_status,
  has_outstanding_fees boolean NOT NULL DEFAULT false,
  outstanding_amount numeric DEFAULT 0,
  debt_acknowledged boolean NOT NULL DEFAULT false,
  debt_note text,
  rejection_reason text,
  requested_at timestamp with time zone NOT NULL DEFAULT now(),
  approved_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  from_class text,
  to_class text,
  reason text,
  processed_at timestamp with time zone,
  CONSTRAINT student_transfers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.transfer_debt_flags (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  transfer_id uuid NOT NULL,
  student_id uuid NOT NULL,
  origin_school_id uuid NOT NULL,
  amount_owed numeric NOT NULL,
  description text,
  is_settled boolean NOT NULL DEFAULT false,
  settled_at timestamp with time zone,
  settled_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT transfer_debt_flags_pkey PRIMARY KEY (id),
  CONSTRAINT transfer_debt_flags_transfer_id_fkey FOREIGN KEY (transfer_id) REFERENCES public.student_transfers(id)
);
CREATE TABLE public.graduation_records (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  student_id uuid NOT NULL,
  school_id uuid NOT NULL,
  graduation_year integer NOT NULL,
  final_class text NOT NULL DEFAULT 'SSS3'::text,
  stream USER-DEFINED,
  graduated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT graduation_records_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pdf_exports (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  requested_by uuid NOT NULL,
  school_id uuid,
  document_type USER-DEFINED NOT NULL,
  subject_id uuid,
  file_url text NOT NULL,
  file_name text NOT NULL,
  academic_year text,
  term USER-DEFINED,
  generated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pdf_exports_pkey PRIMARY KEY (id)
);
CREATE TABLE public.school_health_scores (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  school_id uuid NOT NULL,
  score numeric NOT NULL DEFAULT 0,
  fee_collection_rate numeric,
  teacher_activity_rate numeric,
  quiz_participation_rate numeric,
  attendance_rate numeric,
  onboarding_completion_rate numeric,
  score_date date NOT NULL DEFAULT CURRENT_DATE,
  calculated_at timestamp with time zone NOT NULL DEFAULT now(),
  calculated_date date NOT NULL DEFAULT CURRENT_DATE,
  CONSTRAINT school_health_scores_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid,
  author_id uuid,
  title text NOT NULL,
  subject text,
  file_url text,
  class_level text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.quiz_questions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quiz_id uuid,
  text text NOT NULL,
  options jsonb NOT NULL DEFAULT '[]'::jsonb,
  correct_option integer DEFAULT 0,
  points integer DEFAULT 1,
  order integer DEFAULT 0,
  question text,
  answer text,
  marks integer DEFAULT 1,
  position integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quiz_questions_pkey PRIMARY KEY (id),
  CONSTRAINT quiz_questions_quiz_id_fkey FOREIGN KEY (quiz_id) REFERENCES public.quizzes(id)
);
CREATE TABLE public.quiz_attempts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quiz_id uuid,
  student_id uuid,
  school_id uuid,
  answers jsonb DEFAULT '{}'::jsonb,
  score numeric DEFAULT 0,
  max_score numeric DEFAULT 0,
  submitted_at timestamp with time zone DEFAULT now(),
  started_at timestamp with time zone DEFAULT now(),
  completed boolean NOT NULL DEFAULT false,
  CONSTRAINT quiz_attempts_pkey PRIMARY KEY (id),
  CONSTRAINT quiz_attempts_quiz_id_fkey FOREIGN KEY (quiz_id) REFERENCES public.quizzes(id)
);
CREATE TABLE public.live_classes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid,
  teacher_id uuid,
  title text NOT NULL,
  subject text,
  class_level text,
  status text DEFAULT 'scheduled'::text CHECK (status = ANY (ARRAY['scheduled'::text, 'live'::text, 'ended'::text])),
  meet_url text,
  recording_url text,
  scheduled_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  class_subject_id uuid,
  class_id uuid,
  description text,
  meeting_url text,
  platform text DEFAULT 'zoom'::text,
  is_live boolean NOT NULL DEFAULT false,
  ended_at timestamp with time zone,
  CONSTRAINT live_classes_pkey PRIMARY KEY (id),
  CONSTRAINT live_classes_class_subject_id_fkey FOREIGN KEY (class_subject_id) REFERENCES public.class_subjects(id),
  CONSTRAINT live_classes_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id)
);
CREATE TABLE public.syllabus_topics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  syllabus_id uuid,
  title text NOT NULL,
  week integer DEFAULT 1,
  is_completed boolean DEFAULT false,
  notes text,
  class_subject_id uuid,
  description text,
  week_number integer DEFAULT 1,
  is_covered boolean DEFAULT false,
  covered_at timestamp with time zone,
  term text,
  academic_year text,
  school_id uuid,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT syllabus_topics_pkey PRIMARY KEY (id),
  CONSTRAINT syllabus_topics_syllabus_id_fkey FOREIGN KEY (syllabus_id) REFERENCES public.syllabus(id),
  CONSTRAINT syllabus_topics_class_subject_id_fkey FOREIGN KEY (class_subject_id) REFERENCES public.class_subjects(id),
  CONSTRAINT syllabus_topics_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  room_id uuid,
  sender_id uuid,
  body text NOT NULL,
  type text DEFAULT 'text'::text CHECK (type = ANY (ARRAY['text'::text, 'audio'::text, 'image'::text, 'file'::text])),
  audio_url text,
  file_url text,
  file_name text,
  reactions jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.chat_rooms(id)
);
CREATE TABLE public.study_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid,
  school_id uuid,
  day text NOT NULL,
  subject text NOT NULL,
  time text NOT NULL,
  duration_mins integer DEFAULT 60,
  color text DEFAULT '#7C3AED'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT study_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.school_fees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid,
  student_id uuid,
  amount_ngn numeric NOT NULL,
  paid_ngn numeric DEFAULT 0,
  term text DEFAULT '1st Term'::text,
  session text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'partial'::text, 'paid'::text])),
  due_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  class_level text,
  academic_year text,
  fee_type text DEFAULT 'school_fees'::text,
  amount numeric,
  description text,
  CONSTRAINT school_fees_pkey PRIMARY KEY (id)
);
CREATE TABLE public.alumni (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid,
  full_name text NOT NULL,
  graduation_year integer,
  occupation text,
  company text,
  location text,
  avatar_url text,
  linkedin_url text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT alumni_pkey PRIMARY KEY (id)
);
CREATE TABLE public.behaviour_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid,
  student_id uuid,
  recorded_by uuid,
  type text DEFAULT 'neutral'::text CHECK (type = ANY (ARRAY['positive'::text, 'negative'::text, 'neutral'::text])),
  description text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT behaviour_records_pkey PRIMARY KEY (id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid,
  title text NOT NULL,
  description text,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  event_date date,
  event_time time without time zone,
  event_type text NOT NULL DEFAULT 'general'::text,
  audience text NOT NULL DEFAULT 'all'::text,
  all_day boolean NOT NULL DEFAULT false,
  location text,
  CONSTRAINT events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.schools (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  address text,
  phone text,
  email text,
  primary_color text NOT NULL DEFAULT '#7C3AED'::text,
  setup_status text NOT NULL DEFAULT 'trial'::text,
  trial_started_at timestamp with time zone,
  trial_ends_at timestamp with time zone,
  trial_extended boolean NOT NULL DEFAULT false,
  setup_paid_at timestamp with time zone,
  free_term_starts timestamp with time zone,
  free_term_ends timestamp with time zone,
  subscription_plan USER-DEFINED,
  subscription_starts timestamp with time zone,
  subscription_ends timestamp with time zone,
  next_payment_due timestamp with time zone,
  installment_count integer NOT NULL DEFAULT 0,
  notes text,
  created_by_admin uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  trial_active_score integer DEFAULT 0,
  total_students integer DEFAULT 0,
  bank_name text,
  account_number text,
  account_name text,
  city text,
  state text,
  school_type text NOT NULL DEFAULT 'private'::text,
  is_platform_active boolean NOT NULL DEFAULT true,
  logo_url text,
  tagline text,
  country text DEFAULT 'Nigeria'::text,
  font_family text DEFAULT 'DM Sans'::text,
  status text DEFAULT 'pending'::text,
  principal_id uuid,
  term_duration_months integer NOT NULL DEFAULT 4 CHECK (term_duration_months = ANY (ARRAY[3, 4])),
  build_image_url text,
  free_month_starts timestamp with time zone,
  free_month_ends timestamp with time zone,
  secondary_color text,
  login_bg_image text,
  currency_primary text NOT NULL DEFAULT 'NGN'::text,
  currency_secondary text,
  paystack_subaccount_code text,
  paystack_subaccount_id text,
  paystack_subaccount_active boolean NOT NULL DEFAULT false,
  CONSTRAINT schools_pkey PRIMARY KEY (id),
  CONSTRAINT schools_created_by_admin_fkey FOREIGN KEY (created_by_admin) REFERENCES auth.users(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid,
  full_name text NOT NULL,
  email text NOT NULL,
  phone text,
  role text NOT NULL,
  default_code text,
  onboarding_stage text NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_active boolean NOT NULL DEFAULT true,
  avatar_url text,
  nin text,
  temp_password text,
  employee_id text,
  qualification text,
  years_experience integer,
  subjects_taught ARRAY,
  teacher_role_type USER-DEFINED,
  subject text,
  class_level text,
  admission_number text,
  date_of_birth date,
  gender text,
  graduation_year text,
  lifecycle_stage text DEFAULT 'active'::text,
  last_activity timestamp with time zone,
  last_action text,
  class_id uuid,
  subject_specialty text,
  state text,
  address text,
  pin_hash text,
  permanent_student_id text,
  lifecycle_status text DEFAULT 'active'::text,
  nin_number text,
  parent_id uuid,
  student_number text,
  secret_identifier text,
  nin_verified boolean DEFAULT false,
  nin_verified_at timestamp with time zone,
  nin_screenshot_url text,
  signature_url text,
  notify_whatsapp boolean NOT NULL DEFAULT true,
  notify_sms boolean NOT NULL DEFAULT true,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT profiles_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT profiles_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.school_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL,
  payment_type USER-DEFINED NOT NULL,
  plan USER-DEFINED,
  amount_ngn numeric NOT NULL,
  payment_ref text,
  confirmed_by uuid,
  confirmed_at timestamp with time zone NOT NULL DEFAULT now(),
  term_name text,
  academic_year text,
  CONSTRAINT school_payments_pkey PRIMARY KEY (id),
  CONSTRAINT school_payments_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT school_payments_confirmed_by_fkey FOREIGN KEY (confirmed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  body text NOT NULL,
  type text NOT NULL DEFAULT 'system'::text,
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  school_id uuid,
  link_url text,
  action_url text,
  reference_id uuid,
  reference_table text,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.subscription_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  price_ngn numeric NOT NULL,
  price_per_user_ngn numeric NOT NULL DEFAULT 0,
  billing_cycle text NOT NULL DEFAULT 'monthly'::text,
  features jsonb NOT NULL DEFAULT '[]'::jsonb,
  student_limit integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  is_popular boolean NOT NULL DEFAULT false,
  color text NOT NULL DEFAULT '#7C3AED'::text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT subscription_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.trial_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  default_days integer NOT NULL DEFAULT 10,
  grace_hours integer NOT NULL DEFAULT 48,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trial_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.installment_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  months integer NOT NULL DEFAULT 3,
  discount_pct numeric NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT installment_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.setup_fee_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  amount_ngn numeric NOT NULL DEFAULT 50000,
  is_required boolean NOT NULL DEFAULT true,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT setup_fee_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.trial_reminders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL,
  day_trigger integer NOT NULL,
  sent_at timestamp with time zone DEFAULT now(),
  channel text DEFAULT 'notification'::text,
  CONSTRAINT trial_reminders_pkey PRIMARY KEY (id),
  CONSTRAINT trial_reminders_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.fee_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL,
  student_id uuid,
  student_name text NOT NULL,
  class_level text,
  amount numeric NOT NULL,
  term text NOT NULL CHECK (term = ANY (ARRAY['First Term'::text, 'Second Term'::text, 'Third Term'::text])),
  academic_year text NOT NULL,
  fee_type text NOT NULL DEFAULT 'school_fees'::text CHECK (fee_type = ANY (ARRAY['school_fees'::text, 'development_levy'::text, 'pta'::text, 'uniform'::text, 'other'::text])),
  payment_method text NOT NULL DEFAULT 'bank_transfer'::text CHECK (payment_method = ANY (ARRAY['bank_transfer'::text, 'cash'::text, 'pos'::text])),
  reference text,
  receipt_number text,
  recorded_by uuid,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fee_payments_pkey PRIMARY KEY (id),
  CONSTRAINT fee_payments_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT fee_payments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT fee_payments_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL,
  applicant_name text NOT NULL,
  gender text,
  class_applying_for text,
  parent_name text,
  parent_phone text,
  parent_email text,
  previous_school text,
  notes text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'admitted'::text, 'rejected'::text])),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT applications_pkey PRIMARY KEY (id),
  CONSTRAINT applications_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT applications_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.school_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL,
  title text NOT NULL,
  content text,
  category text NOT NULL DEFAULT 'general'::text CHECK (category = ANY (ARRAY['General'::text, 'Admissions'::text, 'Academic'::text, 'Finance'::text, 'Legal'::text, 'HR'::text, 'Other'::text])),
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  file_url text,
  file_size bigint,
  CONSTRAINT school_documents_pkey PRIMARY KEY (id),
  CONSTRAINT school_documents_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT school_documents_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.class_teachers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL,
  teacher_id uuid NOT NULL,
  class_id uuid NOT NULL,
  subject text,
  role_type USER-DEFINED NOT NULL DEFAULT 'subject_teacher'::teacher_role_type,
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT class_teachers_pkey PRIMARY KEY (id),
  CONSTRAINT class_teachers_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT class_teachers_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.profiles(id),
  CONSTRAINT class_teachers_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id)
);
CREATE TABLE public.meetings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL,
  created_by uuid NOT NULL,
  title text NOT NULL,
  meeting_type text NOT NULL DEFAULT 'pta'::text,
  scheduled_at timestamp with time zone NOT NULL,
  location text,
  meeting_url text,
  agenda text,
  target_audience text NOT NULL DEFAULT 'all_parents'::text,
  target_class_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT meetings_pkey PRIMARY KEY (id),
  CONSTRAINT meetings_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT meetings_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT meetings_target_class_id_fkey FOREIGN KEY (target_class_id) REFERENCES public.classes(id)
);
CREATE TABLE public.principal_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  school_id uuid,
  staff_id text,
  joined_date date,
  CONSTRAINT principal_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT principal_profiles_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.subjects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL,
  name text NOT NULL,
  code text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subjects_pkey PRIMARY KEY (id),
  CONSTRAINT subjects_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.admissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid,
  applicant_name text NOT NULL,
  applicant_email text,
  class_applied text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'waitlisted'::text])),
  notes text,
  applied_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.school_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  school_id uuid,
  title text NOT NULL,
  event_type text NOT NULL DEFAULT 'Academic'::text,
  start_date date NOT NULL,
  end_date date,
  description text,
  all_day boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT school_events_pkey PRIMARY KEY (id),
  CONSTRAINT school_events_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.school_branding(id)
);
CREATE TABLE public.school_expenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL,
  created_by uuid NOT NULL,
  title text NOT NULL,
  category text NOT NULL DEFAULT 'other'::text,
  amount numeric NOT NULL,
  term text NOT NULL,
  academic_year text NOT NULL,
  description text,
  paid_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT school_expenses_pkey PRIMARY KEY (id),
  CONSTRAINT school_expenses_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT school_expenses_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.push_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  school_id uuid,
  endpoint text NOT NULL UNIQUE,
  p256dh text NOT NULL,
  auth text NOT NULL,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  last_used_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT push_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT push_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT push_subscriptions_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.payment_claims (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  school_id uuid NOT NULL,
  parent_id uuid NOT NULL,
  student_id uuid NOT NULL,
  invoice_id uuid,
  fee_type text NOT NULL DEFAULT 'school_fees'::text,
  term text NOT NULL,
  academic_year text NOT NULL,
  amount_claimed numeric NOT NULL,
  currency text NOT NULL DEFAULT 'NGN'::text,
  bank_used text,
  payment_date date,
  notes text,
  proof_url text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'rejected'::text])),
  bursar_note text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_claims_pkey PRIMARY KEY (id),
  CONSTRAINT payment_claims_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT payment_claims_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.profiles(id),
  CONSTRAINT payment_claims_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT payment_claims_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.payment_invoices(id),
  CONSTRAINT payment_claims_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.transcript_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  school_id uuid NOT NULL,
  student_id uuid,
  requested_by uuid,
  purpose text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'ready'::text, 'collected'::text])),
  notes text,
  requested_at timestamp with time zone NOT NULL DEFAULT now(),
  ready_at timestamp with time zone,
  CONSTRAINT transcript_requests_pkey PRIMARY KEY (id),
  CONSTRAINT transcript_requests_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT transcript_requests_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT transcript_requests_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.school_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  school_id text NOT NULL,
  school_name text NOT NULL DEFAULT 'My School'::text,
  current_term text NOT NULL DEFAULT 'First Term'::text,
  current_year text NOT NULL DEFAULT '2025/2026'::text,
  logo_url text,
  address text,
  phone text,
  email text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT school_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscription_payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  school_id uuid NOT NULL,
  amount_paid numeric NOT NULL,
  currency_used text NOT NULL DEFAULT 'NGN'::text,
  plan_type text NOT NULL,
  student_count integer,
  term text,
  academic_year text,
  receipt_number text NOT NULL UNIQUE,
  paystack_reference text,
  paid_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT subscription_payments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.scheduled_reminders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  school_id uuid NOT NULL,
  source_type text NOT NULL CHECK (source_type = ANY (ARRAY['timetable'::text, 'live_class'::text])),
  source_id uuid NOT NULL,
  fire_at timestamp with time zone NOT NULL,
  title text NOT NULL,
  body text NOT NULL,
  url text NOT NULL DEFAULT '/'::text,
  fired boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT scheduled_reminders_pkey PRIMARY KEY (id),
  CONSTRAINT scheduled_reminders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.paystack_webhook_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  event_type text NOT NULL,
  reference text,
  payload jsonb NOT NULL,
  processed boolean NOT NULL DEFAULT false,
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT paystack_webhook_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.school_compliance_records (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  school_id uuid NOT NULL UNIQUE,
  contact_name text,
  contact_role text,
  contact_phone text,
  contact_email text,
  verified_bank_name text,
  verified_account_number text,
  verified_account_name text,
  is_verified boolean NOT NULL DEFAULT false,
  verified_by uuid,
  verified_at timestamp with time zone,
  verification_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT school_compliance_records_pkey PRIMARY KEY (id),
  CONSTRAINT school_compliance_records_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT school_compliance_records_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.recent_activities (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  school_id uuid NOT NULL,
  type text NOT NULL,
  title text NOT NULL,
  subtitle text,
  href text NOT NULL,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT recent_activities_pkey PRIMARY KEY (id),
  CONSTRAINT recent_activities_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT recent_activities_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.ai_rate_limits (
  user_id uuid NOT NULL,
  window_start timestamp with time zone NOT NULL DEFAULT now(),
  request_count integer NOT NULL DEFAULT 0,
  CONSTRAINT ai_rate_limits_pkey PRIMARY KEY (user_id)
);
CREATE TABLE public.report_cards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  class_id uuid NOT NULL,
  school_id uuid NOT NULL,
  term text NOT NULL,
  academic_year text NOT NULL,
  attendance_start_date date,
  attendance_end_date date,
  class_teacher_remark text,
  principal_remark text,
  status text NOT NULL DEFAULT 'draft'::text,
  generated_by uuid,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT report_cards_pkey PRIMARY KEY (id),
  CONSTRAINT report_cards_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT report_cards_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT report_cards_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT report_cards_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES public.profiles(id),
  CONSTRAINT report_cards_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.unread_digest_state (
  user_id uuid NOT NULL,
  last_nudged_at timestamp with time zone,
  nudge_stage integer NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT unread_digest_state_pkey PRIMARY KEY (user_id),
  CONSTRAINT unread_digest_state_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.notification_deliveries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid,
  recipient_id uuid,
  notification_id uuid,
  channel text NOT NULL CHECK (channel = ANY (ARRAY['sms'::text, 'whatsapp'::text])),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'sent'::text, 'failed'::text])),
  to_phone text NOT NULL,
  message_body text NOT NULL,
  provider text NOT NULL DEFAULT 'termii'::text,
  provider_message_id text,
  error text,
  reference_table text,
  reference_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  sent_at timestamp with time zone,
  CONSTRAINT notification_deliveries_pkey PRIMARY KEY (id),
  CONSTRAINT notification_deliveries_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT notification_deliveries_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.profiles(id),
  CONSTRAINT notification_deliveries_notification_id_fkey FOREIGN KEY (notification_id) REFERENCES public.notifications(id)
);
CREATE TABLE public.library_books (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL,
  title text NOT NULL,
  author text,
  isbn text,
  category text NOT NULL DEFAULT 'General'::text CHECK (category = ANY (ARRAY['General'::text, 'Fiction'::text, 'Non-Fiction'::text, 'Textbook'::text, 'Reference'::text, 'Periodical'::text])),
  publisher text,
  cover_url text,
  shelf_location text,
  total_copies integer NOT NULL DEFAULT 1 CHECK (total_copies >= 0),
  available_copies integer NOT NULL DEFAULT 1 CHECK (available_copies >= 0),
  added_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT library_books_pkey PRIMARY KEY (id),
  CONSTRAINT library_books_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT library_books_added_by_fkey FOREIGN KEY (added_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.library_loans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL,
  book_id uuid NOT NULL,
  student_id uuid NOT NULL,
  issued_by uuid,
  borrowed_at timestamp with time zone NOT NULL DEFAULT now(),
  due_at timestamp with time zone NOT NULL,
  returned_at timestamp with time zone,
  status text NOT NULL DEFAULT 'borrowed'::text CHECK (status = ANY (ARRAY['borrowed'::text, 'returned'::text, 'overdue'::text, 'lost'::text])),
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT library_loans_pkey PRIMARY KEY (id),
  CONSTRAINT library_loans_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT library_loans_book_id_fkey FOREIGN KEY (book_id) REFERENCES public.library_books(id),
  CONSTRAINT library_loans_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT library_loans_issued_by_fkey FOREIGN KEY (issued_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.student_medical_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL,
  student_id uuid NOT NULL UNIQUE,
  blood_group text,
  allergies text,
  chronic_conditions text,
  current_medications text,
  emergency_contact_name text,
  emergency_contact_phone text,
  emergency_contact_relationship text,
  physician_name text,
  physician_phone text,
  notes text,
  updated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT student_medical_records_pkey PRIMARY KEY (id),
  CONSTRAINT student_medical_records_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT student_medical_records_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT student_medical_records_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.clinic_visits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL,
  student_id uuid NOT NULL,
  visited_at timestamp with time zone NOT NULL DEFAULT now(),
  reason text NOT NULL,
  symptoms text,
  treatment_given text,
  medication_administered text,
  temperature_c numeric,
  sent_home boolean NOT NULL DEFAULT false,
  parent_notified boolean NOT NULL DEFAULT false,
  parent_notified_at timestamp with time zone,
  follow_up_notes text,
  recorded_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT clinic_visits_pkey PRIMARY KEY (id),
  CONSTRAINT clinic_visits_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT clinic_visits_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id),
  CONSTRAINT clinic_visits_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.profiles(id)
);